apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  restartPolicy: Never
  containers:
  - name: myapp
    image: artursul95/guess-number:latest
    imagePullPolicy: Always
    stdin: true
    tty: true